### ISSUE TITLE
安装不过

### ISSUE THREAD

**Issue by huanchangfjx** [yaofly2012/ymock#1]
问一下，ymock是用windows开发的么，我这边用mac os安装运行 ymock init的话 会说
env: node\r: No such file or directory
然后 我用dos2unix转了一下 cli.js文件 又爆
Error: Cannot find module 'commander'
方便的话 能留个通讯方式么。

谢谢！

**Comment by yaofly2012** [comment]
是在windows开发的，先解决了Error: Cannot find module 'commander'。 Mac上稍后解决下

**Comment by yaofly2012** [comment]
在mac OS重新发布下npm包，好像就没有这个问题了，可以试试：
env: node\r: No such file or directory
囧....
微信：IChattingYou
